---
title: "a_new_hope"
author: "Gulbrand Galaasen"
date: "2024-05-09"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Research question:

What are the drivers for over seas exchange from Norway, and how will the future exchange look taking into account different fundamental changes in Norwegian generation and consumption, and variable renewable energy in northern continental Europe and UK.  



```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(zoo)
library(lubridate)
library(janitor)
library(hablar)
library(tsibble)
library(fpp3)
library(tseries)
```

```{r}
# Where our data ends
CUT_OFF <- "2024-05-01"

# The areas/connections-to we study
areas <- c("DE", "DK", "NL", "UK")

# Bidding zones for Norwegian day-ahead electricity prices
Bidding_zone <- c("NO1", "NO2", "NO3", "NO4", "NO5")

# Dates for when connections were fully operational
DE_conn <- "2021-05-27"
UK_conn <- "2021-10-01"
```


```{r}
# Prices
dayAheadPrices <- function(Bidding_zone, year) {
  read_csv(paste0("data/Norwegian_Day_Ahead_prices/DA_price_", Bidding_zone, "_", year, ".csv"),show_col_types = FALSE) %>% 
    .[,c(1,2)] %>% 
     `colnames<-`(c("date", "price")) %>% 
    separate(date, sep="-", into=c("date", NULL)) %>% 
    mutate(date = as.Date(date, "%d.%m.%Y %H:%M")) %>% 
    mutate(price = as.double(price),
           Bidding_zone = Bidding_zone) %>%
    group_by(date) %>%
    filter(date < as.Date(CUT_OFF)) %>%
    summarise(price = mean(price), Bidding_zone = unique(Bidding_zone))
}

gather_dayAheadPrices <- function(Bidding_zone) {
  map2(rep(Bidding_zone, 7), c("2018":"2024"), dayAheadPrices) %>% 
    bind_rows()
}


# Exchange
cross_border_flow <- function(area, year) {
  read_csv(paste0("data/exchange/", area, "_", year, ".csv"), show_col_types = FALSE) %>% 
    .[,c(1,2,3)] %>% 
     `colnames<-`(c("date", "import", "export")) %>% 
    separate(date, sep="-", into=c("date", NULL)) %>% 
    mutate(import = as.double(import, na.rm = TRUE),
           export = as.double(export, na.rm = TRUE)) %>% 
    mutate(date = as.Date(date, "%d.%m.%Y %H:%M")) %>% 
    group_by(date) %>%
    summarize(exchange = mean(import, na.rm = TRUE) - mean(export, na.rm = TRUE)) %>% 
    mutate(area = area) %>% 
    filter(date < as.Date(CUT_OFF))
}

gather_cross_flow <- function(area) {
  map2(rep(area, 7), c("2018":"2024"), cross_border_flow) %>% 
    bind_rows()
}


# Consumption
gather_load <- function(area, year) {
  read_csv(paste0("data/load_", area, "/load_", area, "_", year, ".csv")) %>% 
    .[,c(1,3)] %>% 
    `colnames<-`(c("date", "load")) %>% 
    drop_na() %>% 
    separate(date, sep="-", into=c("date", NULL)) %>% 
    mutate(date = as.Date(date, "%d.%m.%Y %H:%M")) %>% 
    mutate(load = as.double(load)) %>%
    group_by(date) %>% 
    summarize(load = mean(load)) %>% 
    filter(date < as.Date(CUT_OFF))
}

gather_load_area <- function(area) {
  map2(rep(area, 7), c("2018":"2024"), gather_load) %>% 
    bind_rows() %>%  
    mutate(area = area)
}

# Generation
gather_generation <- function(area, year) {
  if (area == "NO") {
    read_csv(paste0("data/generation/gen_", area, "/gen_", area, "_", year, ".csv"), na = c("n/e", "N/A", "-")) %>% 
      .[,2:23] %>% 
      mutate(gen = rowSums(.[,2:22], na.rm = TRUE)) %>% 
      select(MTU, gen) %>% 
      rename(date = MTU) %>% 
      drop_na() %>% 
      separate(date, sep="-", into=c("date", NULL)) %>%
      mutate(date = as.Date(date, "%d.%m.%Y %H:%M")) %>% 
      group_by(date) %>% 
      summarize(gen = mean(gen)) %>% 
      filter(date < as.Date(CUT_OFF))
      
  } else {
    read_csv(paste0("data/generation/gen_", area, "/gen_", area, "_", year, ".csv")) %>% 
      .[,c(2,20,22,23)] %>% 
      `colnames<-`(c("date", "sol", "wnd_off", "wnd_on")) %>% 
      drop_na() %>% 
      separate(date, sep="-", into=c("date", NULL)) %>% 
      mutate(vrep = as.double(sol) + as.double(wnd_off) + as.double(wnd_on)) %>%
      mutate(date = as.Date(date, "%d.%m.%Y %H:%M")) %>% 
      group_by(date) %>% 
      summarize(vrep = mean(vrep)) %>% 
      filter(date < as.Date(CUT_OFF))
  }
}

gather_generation_area <- function(area) {
  # Special case for UK data as these are not present in Etsoe because of Brexit
  if (area == "UK") {
    read_csv(paste0("data/generation/gen_", area, "/gen_", area, ".csv")) %>% 
      .[,c(3,6,7)] %>% 
      `colnames<-`(c("date", "type", "vrep")) %>%
      filter(type %in% c("WIND")) %>% 
      mutate(vrep = as.double(vrep)) %>% 
      mutate(date = as.Date(with_tz(date, tzone = "Europe/Oslo"), tz = "Europe/Oslo")) %>% 
      group_by(date) %>%
      summarize(vrep = mean(vrep, na.rm = TRUE)) %>% 
      arrange(date) %>% 
      filter(date < as.Date(CUT_OFF)) %>% 
      mutate(area = area)
      
  } else {
    map2(rep(area, 7), c("2018":"2024"), gather_generation) %>% 
      bind_rows() %>%  
      mutate(area = area) 
  }
}
```

```{r, warning=FALSE, message=FALSE}
# Gather data

# Prices
price <- map(Bidding_zone, gather_dayAheadPrices) %>%
  bind_rows() %>% 
  group_by(date) %>% 
  summarise(price = mean(price))

# Exchange
exchange <- map(areas, gather_cross_flow) %>%
  bind_rows()

# Consumption
load_NO <- gather_load_area("NO")

# Generation
gen_NO <- gather_generation_area("NO")

# Variable renewable production
vrep <- map(areas, gather_generation_area) %>% 
  bind_rows()
```

```{r}
df <- exchange %>% 
  inner_join(., vrep, by = c("date", "area")) %>% 
  inner_join(., gen_NO[,c(1,2)], by = c("date")) %>% 
  inner_join(., load_NO[,c(1,2)], by = c("date")) %>% 
  inner_join(., price[,c(1,2)], by = c("date"))

is.nan.data.frame <- function(x)
do.call(cbind, lapply(x, is.nan))
df[is.nan(df)] <- 0
```


```{r}
res <- map(c("SE", "FI"), gather_cross_flow) %>%
  bind_rows() %>% 
  group_by(date) %>% 
  summarise(exchange = sum(exchange))

df %>% 
  #filter(area != "DE") %>% 
  group_by(date) %>% 
  summarise(exchange = sum(exchange),
            gen = first(gen),
            load = first(load)) %>% 
  mutate(exchange = exchange + res$exchange,
         tot = gen + exchange - load) %>% 
  ggplot() +
  geom_line(aes(x = date, y = tot, color = "tot")) +
  geom_line(aes(x = date, y = load, color = "load")) + 
  geom_line(aes(x = date, y = exchange, color = "exchange"))
```


Forecast

```{r}

```

