---
title: "Untitled"
author: "Matias Kongsvik"
date: "2024-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(zoo)
library(lubridate)
library(janitor)
library(hablar)
library(tsibble)
library(fpp3)
library(tseries)
library(dynlm)
library(ggplot2)
```

```{r}
CUT_OFF <- "2024-05-01"
countries <- c("de", "dk", "nl", "swe", "fin")

```


Dependent variable: Cross Border Flow
```{r, warning=FALSE}

cross_border_flow <- function(country, year) {
  read_csv(paste0("Cross Border Flow/", country, "_", year, ".csv"),show_col_types = FALSE) %>% 
    .[,c(1,2,3)] %>% 
     `colnames<-`(c("date", "import", "export")) %>% 
    separate(date, sep="-", into=c("date", NULL)) %>% 
    mutate(date = as.Date(date, "%d.%m.%Y %H:%M")) %>% 
    mutate(import = as.double(import),
           export = as.double(export),
           country = as.character(paste0(country))) %>% 
    group_by(date) %>%
    summarize(exchange = sum(import, na.rm = TRUE) - sum(export, na.rm = TRUE)) %>% 
    mutate(country = country)
}
df <- cross_border_flow("uk", "2018")

gather_cross_flow <- function(country) {
  map2(rep(country, 7), c("2018":"2024"), cross_border_flow) %>% 
    bind_rows()
}

df <- gather_cross_flow("uk")

cross_border_flow_all <- map(c("uk", "nl", "ger", "den"), gather_cross_flow) %>%
  bind_rows()

# gather_cross_flow <- function(country) {
#   if(country == "uk") {
#     read_csv(paste0("Cross Border Flow/", country, ".csv"), show_col_types = FALSE) %>% 
#       .[,c(3,6,7)] %>% 
#       `colnames<-`(c("date", "type", "net_export")) %>% 
#       filter(type %in% c("INTNSL")) %>% 
#       mutate(date = as.Date(with_tz(date, tzone = "Europe/Oslo"), tz = "Europe/Oslo")) %>%
#       group_by(date) %>%
#       summarize(net_export = sum(as.double(-net_export), na.rm = TRUE)) %>%
#       arrange(date) %>%
#       filter(date < as.Date(CUT_OFF)) %>%
#       mutate(country = country)
#       
#   } else {
#   map2(rep(country, 7), c("2018":"2024"), cross_border_flow)
#     bind_rows() 
#   }
# }

gather_cross_flow("ger") %>% print()

cross_border_flow_all <- map(c("swe", "den", "ger", "nl", "fin"), gather_cross_flow) %>% 
  bind_rows()
               

```


Target variable: Daily hydro generation. 

```{r, warning = FALSE, message = FALSE}
# Generation
gather_generation <- function(area, year) {
  read_csv(paste0("Generation/Generation_", year, "_", area, ".csv")) %>% 
    .[,c(2,15)] %>% 
     `colnames<-`(c("date", "hydro")) %>% 
    separate(date, sep="-", into=c("date", NULL)) %>% 
    mutate(date = as.Date(date, "%d.%m.%Y %H:%M")) %>% 
    mutate(hydro = as.double(hydro)) %>%  
    group_by(date) %>% 
    summarize(hydro = mean(hydro, na.rm = TRUE))
}

gather_generation_area <- function(area) {
  map2(rep(area, 10), c("2015":"2024"), gather_generation) %>% 
    bind_rows() 
}

gen_level <- gather_generation_area("NO1") %>% 
  rename("NO1" = "hydro") %>% 
  mutate("NO2" = gather_generation_area("NO2")$hydro,
         "NO5" = gather_generation_area("NO5")$hydro)
```


Weekly reservoir data.

```{r, warning = FALSE, message = FALSE}
# Reservoir levels
gather_res_lev <- function(area) {
  read_csv(paste0("Fyllingsgrad/Fyllingsgrad_", area, ".csv")) %>% 
    gather(key = "year", value = level, -Uke) %>% 
    drop_na() %>% 
    mutate(yw = yearweek(paste0(year, " W", Uke))) %>% 
    select(-Uke, -year) %>% 
    mutate(level = as.double(unlist(strsplit(level, "%"))) / 100) %>% 
    select(yw, level) %>% 
    arrange(yw)
}

res_level <- gather_res_lev("NO1") %>% 
  rename(NO1 = level) %>% 
  mutate(NO2 = gather_res_lev("NO2")$level, 
         NO5 = gather_res_lev("NO5")$level)
```

Daily price data.

```{r, warning = FALSE, message = FALSE}
# Price
gather_price <- function(area, year) {
  read_csv(paste0("Price/Price_", year, "_", area, ".csv")) %>% 
    .[,c(1,2)] %>% 
    `colnames<-`(c("date", "price")) %>% 
    separate(date, sep="-", into=c("date", NULL)) %>%
    # Subtract one day from date 
    mutate(date = as.Date(date, "%d.%m.%Y %H:%M") - as.difftime(1, unit="days")) %>% 
    mutate(price = as.double(price)) %>%  
    group_by(date) %>% 
    summarize(price = mean(price, na.rm = TRUE))
}

gather_price_area <- function(area) {
  map2(rep(area, 10), c("2015":"2024"), gather_price) %>% 
    bind_rows()
}

price_level <- gather_price_area("NO1") %>% 
  rename("NO1" = "price") %>% 
  mutate("NO2" = gather_price_area("NO2")$price,
         "NO5" = gather_price_area("NO5")$price)
```


```{r}
create_data <- function(area) {
  df <- 
    gen_level[,c("date", area)] %>% 
    inner_join(., price_level[,c("date", area)], by = "date") %>% 
    mutate(yw = yearweek(date)) %>% 
    inner_join(., res_level[,c("yw", area)], by = "yw") %>% 
    select(-yw) %>% 
    as_tsibble(index = date)
  
  colnames(df) <- c("date", "gen", "pri", "res")

  return(df)
}

create_fit_test <- function(df, sep, fit_test) {
  if (fit_test == "fit") {
    df %>% 
      filter(date < as.Date(sep, "%d-%m-%Y"))
  } else {
    df %>% 
      filter(date >= as.Date(sep, "%d-%m-%Y"))
  }
}

SEP_DATE <- "01-01-2023"

# NO1
NO1 <- create_data("NO1")
fit_NO1 <- create_fit_test(NO1, SEP_DATE, "fit")
test_NO1 <- create_fit_test(NO1, SEP_DATE, "test")

# NO2
NO2 <- create_data("NO2")
fit_NO2 <- create_fit_test(NO2, SEP_DATE, "fit")
test_NO2 <- create_fit_test(NO2, SEP_DATE, "test")

# NO5
NO5 <- create_data("NO5")
fit_NO5 <- create_fit_test(NO5, SEP_DATE, "fit")
test_NO5 <- create_fit_test(NO5, SEP_DATE, "test")

```


```{r}
models <- 
  fit_NO5 %>% 
  fill_gaps() %>%
  model(mod1 = ARIMA(gen ~ res + pri))
```

```{r}
models %>%  gg_tsresiduals()
```


```{r}
glance(models) %>% arrange(AICc)
```
```{r}
models %>% 
  select(mod1) %>% 
  report()

```


```{r}
f <- models %>% 
  forecast(., new_data = test_NO5)
f %>% autoplot(test_NO5)

```

