---
title: "Untitled"
author: "Matias Kongsvik"
date: "2024-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(zoo)
library(lubridate)
library(janitor)
library(hablar)
library(tsibble)
library(fpp3)
library(tseries)
```

Target variable: Weekly hydro generation. 

```{r, warning = FALSE, message = FALSE}
# Generation
gather_generation <- function(area, year) {
  read_csv(paste0("Generation/Generation_", year, "_", area, ".csv")) %>% 
    .[,c(2,15)] %>% 
     `colnames<-`(c("date", "hydro")) %>% 
    separate(date, sep="-", into=c("date", NULL)) %>% 
    mutate(date = as.Date(date, "%d.%m.%Y %H:%M"),
           yw = yearweek(date)) %>% 
    mutate(hydro = as.double(hydro)) %>%  
    group_by(yw) %>% 
    summarize(hydro = mean(hydro, na.rm = TRUE))
}

gather_generation_area <- function(area) {
  map2(rep(area, 10), c("2015":"2024"), gather_generation) %>% 
    bind_rows() %>%  
    group_by(yw) %>% 
    summarize(hydro = mean(hydro, na.rm = TRUE))
}

gen_level <- gather_generation_area("NO1") %>% 
  rename("NO1" = "hydro") %>% 
  mutate("NO2" = gather_generation_area("NO2")$hydro,
         "NO5" = gather_generation_area("NO5")$hydro)
```

Reservoir data.

```{r, warning = FALSE, message = FALSE}
# Reservoir levels
gather_res_lev <- function(area) {
  read_csv(paste0("Fyllingsgrad/Fyllingsgrad_", area, ".csv")) %>% 
    gather(key = "year", value = level, -Uke) %>% 
    drop_na() %>% 
    mutate(yw = yearweek(paste0(year, " W", Uke))) %>% 
    select(-Uke, -year) %>% 
    mutate(level = as.double(unlist(strsplit(level, "%"))) / 100) %>% 
    select(yw, level) %>% 
    arrange(yw)
}

res_level <- gather_res_lev("NO1") %>% 
  rename(NO1 = level) %>% 
  mutate(NO2 = gather_res_lev("NO2")$level, 
         NO5 = gather_res_lev("NO5")$level)
```

```{r, warning = FALSE, message = FALSE}
# Price
gather_price <- function(area, year) {
  read_csv(paste0("Price/Price_", year, "_", area, ".csv")) %>% 
    .[,c(1,2)] %>% 
    `colnames<-`(c("date", "price")) %>% 
    separate(date, sep="-", into=c("date", NULL)) %>%
    # Subtract one day from date 
    mutate(date = as.Date(date, "%d.%m.%Y %H:%M") - as.difftime(1, unit="days"),
           yw = yearweek(date)) %>% 
    mutate(price = as.double(price)) %>%  
    group_by(yw) %>% 
    summarize(price = mean(price, na.rm = TRUE))
}

gather_price_area <- function(area) {
  map2(rep(area, 10), c("2015":"2024"), gather_price) %>% 
    bind_rows() %>% 
    group_by(yw) %>% 
    summarize(price = sum(price, na.rm = TRUE))
}

price_level <- gather_price_area("NO1") %>% 
  rename("NO1" = "price") %>% 
  mutate("NO2" = gather_price_area("NO2")$price,
         "NO5" = gather_price_area("NO5")$price)
```


```{r}
create_data <- function(area) {
  df <- 
    gen_level[,c("yw", area)] %>% 
    inner_join(., price_level[,c("yw", area)], by = "yw") %>% 
    inner_join(., res_level[,c("yw", area)], by = "yw") %>% 
    as_tsibble(index = yw)
  
  colnames(df) <- c("date", "gen", "pri", "res")

  return(df)
}

create_fit_test <- function(df, sep, fit_test) {
  if (fit_test == "fit") {
    df %>% 
      filter(date < yearweek(as.Date(sep, "%d-%m-%Y")))
  } else {
    df %>% 
      filter(date >= yearweek(as.Date(sep, "%d-%m-%Y")))
  }
}

SEP_DATE <- "01-01-2024"

# NO1
NO1 <- create_data("NO1")
fit_NO1 <- create_fit_test(NO1, SEP_DATE, "fit")
test_NO1 <- create_fit_test(NO1, SEP_DATE, "test")

# NO2
NO2 <- create_data("NO2")
fit_NO2 <- create_fit_test(NO2, SEP_DATE, "fit")
test_NO2 <- create_fit_test(NO2, SEP_DATE, "test")

# NO5
NO5 <- create_data("NO5")
fit_NO5 <- create_fit_test(NO5, SEP_DATE, "fit")
test_NO5 <- create_fit_test(NO5, SEP_DATE, "test")

```

```{r}
# NO5
models <- 
  fit_NO1 %>% 
  #fill_gaps() %>%
  model(mod = ARIMA(pri ~ res + gen))

models %>% gg_tsresiduals()

models %>% 
  select(mod) %>% 
  report()

f <- models %>% 
  forecast(., new_data = test_NO1)
f %>% autoplot(NO1)
```
```{r}
f <- models %>% 
  forecast(., new_data = test_NO1)
f %>% autoplot(test_NO1)
```

